//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2_MVCWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rencontre
    {
        public long Id { get; set; }
        public string Equipe1 { get; set; }
        public string Equipe2 { get; set; }
        public Nullable<byte> Score1 { get; set; }
        public Nullable<byte> Score2 { get; set; }
    }
}
